<a href="https://colab.research.google.com/github/Irina0703/SpecialistPython1/blob/master/bootstrap_for_dudes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
!pip install arch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.7/981.7 kB 12.0 MB/s eta 0:00:00


In [ ]:
from arch.bootstrap import IIDBootstrap, IndependentSamplesBootstrap

In [ ]:
rng = np.random.default_rng(111111)
x = rng.normal(loc=5, scale=4, size=20)

In [ ]:
x

array([ 8.75056101,  2.04660955,  5.82436808,  2.81933431,  3.55431834,
        4.36497893, 10.94214485,  6.52441297,  8.72714931,  8.57755903,
        4.47753664,  8.80829036,  5.072406  ,  3.54047913,  5.48872283,
        7.6829816 ,  2.43211183, -3.41245328,  8.78998033, -1.76474929])

$E(X_i) = 5$, $Var(X_i) = 4^2$, $X_i$ независимы.

In [ ]:
np.mean(x)

5.162337126364272

Поиграем в настоящего исследователя, сделаем вид, что мы не знаем $E(X_i)$. Мы можем получить точечную оценку для математического ожидания. Естественная формула, $\bar x = \frac{x_1 +\ldots + x_n}{n}$.

In [ ]:
mu_hat = np.mean(x)
mu_hat

5.162337126364272

Как построить доверительный интервал для неизвестного $\mu = E(X_i)$?
Хочу точечную оценку превратить в интервальную. Достаточно «размножить» точечную оценку.

Выход: из наших $n=20$ наблюдений случайно выберем $20$ с возможностью повтора.

In [ ]:
x_star1 = rng.choice(x, size=len(x))

In [ ]:
x_star1

array([ 5.072406  ,  7.6829816 ,  7.6829816 , 10.94214485,  3.55431834,
        3.55431834,  8.57755903,  3.54047913,  5.82436808,  4.36497893,
        8.75056101,  8.80829036,  8.57755903, -3.41245328,  4.47753664,
        6.52441297,  8.75056101,  2.04660955,  5.82436808,  7.6829816 ])

In [ ]:
np.mean(x_star1)

5.941348143400953

In [ ]:
x_star2 = rng.choice(x, size=len(x))
np.mean(x_star2)

5.382909324145878

In [ ]:
x_star2

array([ 3.55431834,  7.6829816 ,  5.82436808,  3.54047913,  4.36497893,
       10.94214485,  6.52441297,  3.55431834,  8.75056101,  7.6829816 ,
        5.072406  ,  7.6829816 ,  5.82436808,  4.47753664, -1.76474929,
        7.6829816 ,  2.43211183,  2.81933431,  8.57755903,  2.43211183])

In [ ]:
n_boot = 1000
mu_hat_star = [np.mean(rng.choice(x, size=len(x))) for i in range(n_boot)]

In [ ]:
mu_hat_star[1:10]

[6.713233840263672,
 5.617551215067908,
 5.35446519920025,
 5.481905847543931,
 6.692005176307161,
 4.99720648239316,
 5.301918245945239,
 5.211700883514384,
 5.676470991935876]

Наивный бутстрэп доверительный интервал для $\mu=E(X_i)$:

In [ ]:
[np.quantile(mu_hat_star, 0.025), np.quantile(mu_hat_star, 0.975)]

[3.466441480784882, 6.62888113822821]

Плюсы:
1. Мы можем не знать формулы для дисперсии оценки.

Мы не использовали $Var(\hat\mu)$.

2. В большинстве случаев формулы верны при больших $n$.
И бутстрэп тоже требует больших $n$.

Часто оказывается, что большое $n$, нужное для «правильного» варианта бутстрэпа, гораздо меньше, чем большое $n$, нужное для центральной предельной теоремы.

In [ ]:
boot_x = IIDBootstrap(x, seed=111111)
boot_x.conf_int(np.mean, method='basic', reps=10000, size=0.95)

array([[3.67824331],
       [6.76505453]])

In [ ]:
boot_x.conf_int(np.std, method='basic', reps=10000, size=0.95)

array([[2.63833899],
       [4.8650567 ]])

Tim Hestergerg, What teachers should know about bootstrap?

In [ ]:
w = x + rng.normal(loc=1, scale=3, size=len(x))

In [ ]:
np.corrcoef(x, w)

array([[1.        , 0.83265667],
       [0.83265667, 1.        ]])

In [ ]:
def corr(x, y):
  corr_mat = np.corrcoef(x, y)
  return corr_mat[0, 1]

In [ ]:
corr(x, w)

0.8326566707478291

In [ ]:
x

array([ 8.75056101,  2.04660955,  5.82436808,  2.81933431,  3.55431834,
        4.36497893, 10.94214485,  6.52441297,  8.72714931,  8.57755903,
        4.47753664,  8.80829036,  5.072406  ,  3.54047913,  5.48872283,
        7.6829816 ,  2.43211183, -3.41245328,  8.78998033, -1.76474929])

In [ ]:
w

array([11.91168901,  2.56161307, -0.05905122,  5.75234653,  1.9965966 ,
        4.89802143, 13.18925613,  5.94531856, 13.8390005 , 12.39287802,
        2.98500801,  7.49480114,  2.89315956,  7.37127129,  6.71418125,
        7.15422325,  5.34030994, -0.66562737, 11.09626948, -4.77853031])

In [ ]:
obs_id = rng.choice(range(len(x)), size=len(x))
obs_id

array([14,  2, 12,  4,  9, 18, 16, 19,  4,  9,  6, 11, 10, 13, 12,  1,  9,
        9,  2, 12])

In [ ]:
x_star1 = x[obs_id]
x_star1

array([ 5.48872283,  5.82436808,  5.072406  ,  3.55431834,  8.57755903,
        8.78998033,  2.43211183, -1.76474929,  3.55431834,  8.57755903,
       10.94214485,  8.80829036,  4.47753664,  3.54047913,  5.072406  ,
        2.04660955,  8.57755903,  8.57755903,  5.82436808,  5.072406  ])

In [ ]:
w_star1 = w[obs_id]
w_star1

array([ 6.71418125, -0.05905122,  2.89315956,  1.9965966 , 12.39287802,
       11.09626948,  5.34030994, -4.77853031,  1.9965966 , 12.39287802,
       13.18925613,  7.49480114,  2.98500801,  7.37127129,  2.89315956,
        2.56161307, 12.39287802, 12.39287802, -0.05905122,  2.89315956])

In [ ]:
corr(x_star1, w_star1)

0.8248153261423454

In [ ]:
boot_xw = IIDBootstrap(x, w, seed=111111)
boot_xw.conf_int(corr, method='basic', reps=10000, size=0.95)

array([[0.73375844],
       [1.02066742]])

In [ ]:
4 - 3 == 1

True

In [ ]:
0.4 - 0.3 == 0.1

False

In [ ]:
y = rng.normal(loc=9, scale=3, size=25)

In [ ]:
y

array([12.14268681, 12.17501015,  6.73312431, 11.99569635,  5.82977991,
        0.8671864 ,  7.99425006,  8.21486399,  9.23877598,  8.63018244,
        7.6098239 ,  8.11828919,  6.51132991, 13.55765964,  8.7764837 ,
        7.66390195, 10.48363553, 12.94911141,  6.01879175, 11.17176947,
       12.4419654 ,  8.79761341,  5.98529289,  6.86739964,  4.7187951 ])

In [ ]:
def mean_diff(x, y):
  return np.mean(y) - np.mean(x)

In [ ]:
boot_xy = IndependentSamplesBootstrap(x, y, seed=111111)
boot_xy.conf_int(mean_diff, reps=10000, size=0.95, method='basic')

array([[1.53302614],
       [5.35966773]])