<a href="https://colab.research.google.com/github/Irina0703/SpecialistPython1/blob/master/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22bootstrap_for_dudes_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
!pip install arch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.7/981.7 kB 12.0 MB/s eta 0:00:00


In [ ]:
from arch.bootstrap import IIDBootstrap, IndependentSamplesBootstrap

In [ ]:
rng = np.random.default_rng(111111)
x = rng.normal(loc=5, scale=4, size=20)

In [ ]:
x

array([ 8.75056101,  2.04660955,  5.82436808,  2.81933431,  3.55431834,
        4.36497893, 10.94214485,  6.52441297,  8.72714931,  8.57755903,
        4.47753664,  8.80829036,  5.072406  ,  3.54047913,  5.48872283,
        7.6829816 ,  2.43211183, -3.41245328,  8.78998033, -1.76474929])

$E(X_i) = 5$, $Var(X_i) = 4^2$, $X_i$ независимы.

In [ ]:
np.mean(x)

5.162337126364272

Поиграем в настоящего исследователя, сделаем вид, что мы не знаем $E(X_i)$. Мы можем получить точечную оценку для математического ожидания. Естественная формула, $\bar x = \frac{x_1 +\ldots + x_n}{n}$.

In [ ]:
mu_hat = np.mean(x)
mu_hat

5.162337126364272

Как построить доверительный интервал для неизвестного $\mu = E(X_i)$?
Хочу точечную оценку превратить в интервальную. Достаточно «размножить» точечную оценку.

Выход: из наших $n=20$ наблюдений случайно выберем $20$ с возможностью повтора.

In [ ]:
x_star1 = rng.choice(x, size=len(x))

In [ ]:
x_star1

array([ 5.072406  ,  7.6829816 ,  7.6829816 , 10.94214485,  3.55431834,
        3.55431834,  8.57755903,  3.54047913,  5.82436808,  4.36497893,
        8.75056101,  8.80829036,  8.57755903, -3.41245328,  4.47753664,
        6.52441297,  8.75056101,  2.04660955,  5.82436808,  7.6829816 ])

In [ ]:
np.mean(x_star1)

5.941348143400953

In [ ]:
x_star2 = rng.choice(x, size=len(x))
np.mean(x_star2)

5.382909324145878

In [ ]:
x_star2

array([ 3.55431834,  7.6829816 ,  5.82436808,  3.54047913,  4.36497893,
       10.94214485,  6.52441297,  3.55431834,  8.75056101,  7.6829816 ,
        5.072406  ,  7.6829816 ,  5.82436808,  4.47753664, -1.76474929,
        7.6829816 ,  2.43211183,  2.81933431,  8.57755903,  2.43211183])

In [ ]:
n_boot = 1000
mu_hat_star = [np.mean(rng.choice(x, size=len(x))) for i in range(n_boot)]

In [ ]:
mu_hat_star[1:10]

[6.713233840263672,
 5.617551215067908,
 5.35446519920025,
 5.481905847543931,
 6.692005176307161,
 4.99720648239316,
 5.301918245945239,
 5.211700883514384,
 5.676470991935876]